name: upload to registry
# this is for uploading images to a container registry when
# changes are made to `main`

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    env:
      REGISTRY: ghcr.io
      USERNAME: getchoo

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: fetch docker image
        run: |
          nix build --accept-flake-config -L .#container
          readlink result | xargs -I {} cp {} teawiebot.tar.gz

      - name: login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ github.token }}

      - name: upload to registry
        env:
          PUSH_PREFIX: ${{ env.REGISTRY }}/${{ env.USERNAME }}
        run: |
          docker load < teawiebot.tar.gz
          docker tag teawiebot:latest ${{ env.PUSH_PREFIX }}/teawiebot:latest
          docker push ${{ env.PUSH_PREFIX }}/teawiebot:latest
